---
 # Reference files
base:
    dir: "/mnt/scratchb/jmlab/morgan02/Covid"
    run: "TEST"

singularity:
    img: "/mnt/scratchb/jmlab/morgan02/Covid/singularity/CovidPBMC.sif"
    preamble: " -B /mnt/scratchb "

hg38_SarsCov2:
    # the cellranger format file with human and Sars-CoV2 genome sequences and annotations
    referenceFolder: "/mnt/scratchb/jmlab/morgan02/Covid/genome_refs/hg38_SarsCov2"
    fasta: "/mnt/scratchb/jmlab/morgan02/Covid/genome_refs/hg38_SarsCov2/fasta/genome.fa"

hg38_vdj:
    # standard 10X Genomics pre-built Ig and TCR loci
    referenceFolder: "/mnt/scratchb/jmlab/morgan02/Covid/genome_refs/refdata-cellranger-vdj-GRCh38-alts-ensembl-3.1.0"

params:
    featureReference: "/mnt/scratchb/jmlab/morgan02/Covid/test_data/ref_files/vdj_v1_hs_pbmc2_5gex_protein_feature_ref.csv" # assumes this is the same across experiments

emptyDrops:
    umi_threshold: 100
    fdr_threshold: 0.001
    emptydrops_rscript: "/mnt/scratchb/jmlab/morgan02/Covid/CovidPBMC/src/call_cells.R"

genotyper:
    ref_vcf: "/mnt/scratchb/jmlab/morgan02/Covid/genotypes/genomeProject/hg38/genome1K.phase3.SNP_AF5e2.chr1toX.withoutChr.vcf.gz" # input a reference VCF, e.g. 1K Genomes
    min_MAF: 0.1
    min_Count: 20

demux:
    filters: ""

QC:
    mt_thresh: 2 # this is a scalar for how many times the MAD should be treated as outliers
    umi_thresh: 1000 # the minimum number of detected UMIs per cell to keep
    sparsity: 0.99 # the percentage of 0's to tolerate per single-cell (sparsity)
    qc_rscript: "/mnt/scratchb/jmlab/morgan02/Covid/CovidPBMC/src/qc_cells.R"

Norm:
    gene_sparse: 0.95 # the percentages of 0's to tolerate per gene prior to size factor estimation
    norm_rscript: "/mnt/scratchb/jmlab/morgan02/Covid/CovidPBMC/src/norm_data.R"
    qc_flag: "--outputqc"
    positive_factors: " --force " # force size factors to be positive

ADT:
    qc_rscript: "/mnt/scratchb/jmlab/morgan02/Covid/CovidPBMC/src/ADT_report.R"

Conversion:
    bam2fastq: "/hps/nobackup/research/marioni/covid19/CovidPBMC/src/bam2fastq.py"

Reference:
    virus: "NCBI_virus,NCBI_SARS_COV2"

FinalCheck:
  permission_script: "/mnt/scratchb/jmlab/morgan02/Covid/CovidPBMC/src/check_permissions.sh"

...