# # Reference files
base:
    dir: "/hps/nobackup/research/marioni/covid19"
    run: "TEST"
hg38_SarsCov2:
    # the cellranger format file with human and Sars-CoV2 genome sequences and annotations
    referenceFolder: "genome_refs/hg38_SarsCov2"

params:
        cellranger: "" #?

